### ISSUE TITLE
Array of objects with different order produces CSV with unordered columns.

### ISSUE THREAD

**Issue by icarito** [avoidwork/csv.js#7]
```
csv.encode([{proto: 1, moto: 2}, {moto: 'a', proto: 'b'}])
"proto,moto
1,2
a,b"
```

**Comment by icarito** [comment]
Expected result:
```
"proto,moto
1,2
b,a"
```

**Comment by avoidwork** [comment]
yeah, that could be a problem.

**Comment by avoidwork** [comment]
so, just to establish the expectation; the order of the keys on the first object will determine everything.

**Comment by icarito** [comment]
Thank you! FYI I'm using it to save data from a libre app for surveying trees! https://github.com/icarito/arbio-azucar-censa-arbol

**Comment by icarito** [comment]
Initially data came mixed up and I traced it down to this issue, thanks for fixing it.
