### ISSUE TITLE
Is ie9 supported?

### ISSUE THREAD

**Issue by drnkwati** [avoidwork/csv.js#9]
Please include browser support

**Comment by avoidwork** [comment]
I won't be putting in the effort to support an outdated browser; upgrade your OS please.

**Comment by drnkwati** [comment]
Sorry  not for me but end users of my project

**Comment by avoidwork** [comment]
You can pass the message along. I have no incentive.

**Comment by drnkwati** [comment]
No worries. I don't have to use it
